version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge

services:
  apibackend:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS = "http://0.0.0.0:7269"
      - ConnectionStrings__DatabaseContext=Host=host.docker.internal;Port=5432;Database=tickets;Username=postgres;Password=root;
    container_name: apibackend
    image: apopheosis/backendapi
    build: .
    depends_on:
      - database
    hostname: "webapi"
    networks:
      - dockerapi-dev
    ports:
      - "7269:7269"
  proxy:
    container_name: reverse_proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "777:80"
    restart: always
    depends_on:
      - apibackend
    networks:
      - dockerapi-dev
  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=tickets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - dockerapi-dev